language: python
python:
  - "3.6"
install:
 - pip install -r requirements.txt
script:
 - nosetests --with-coverage --cover-package=app && coveralls
after_success:
- coveralls
notifications:
  slack:
    on_success: never
    0n_failure: never